### ISSUE TITLE
Error Occur this.destinationAddress.toJSON is not a function khi ấn nút Empty cart 

### ISSUE THREAD

**Issue by toan15042000** [SWP490-G2/swp490_g2#143]
![image](https://user-images.githubusercontent.com/125334704/235358079-1e748db6-4a88-4630-a4a9-bebc87a62500.png)

**Comment by Tungnguyenn0504** [comment]
Vẫn hoạt động bình thường

**Comment by toan15042000** [comment]
Khi tạo object mới, ví dụ: tạo object `Address` mới. Không nên dùng `new Address()`, vì nó ko populate các child objects.
Nên sử dụng `Address.fromJson({})`. Trong `fromJson` function, nó có call `fromJson` của các child objects nên function này đảm bảo việc tất các các child objects được initialized.
