### ISSUE TITLE
[FE] [Chung cho all screen] Đối với các fields required phải hiển thị thêm dấu * đằng sau màu đỏ

### ISSUE THREAD

**Issue by LuongNVHE130930** [SWP490-G2/swp490_g2#46]
Hiển thị dấu * màu đen với các trường required 

Đối với các fields required phải hiển thị thêm dấu * đằng sau màu đỏ 
![image](https://user-images.githubusercontent.com/62321945/232077251-4feb6140-f9b4-43c5-bc68-dbed9c16e4da.png)

**Comment by toan15042000** [comment]
Use class `.required` for tag `label`.
