### ISSUE TITLE
(Homepage - HP_8) Unable to load categories

### ISSUE THREAD

**Issue by baotq2210** [SWP490-G2/swp490_g2#49]
![image](https://user-images.githubusercontent.com/125334056/232233545-3698f8de-4c1f-45a3-adad-0cc3720d3f31.png)

**Comment by toan15042000** [comment]
![image](https://user-images.githubusercontent.com/125334704/232685170-a83d5572-5150-475a-9b8b-1040b37cd6b3.png)
